dataCode: Cerebellum
sampleKey: input_files/Cerebellum_sample_key.txt
genotypePCs: input_files/Cerebellum_genotype_PCs.txt
covariateFile: input_files/Cerebellum_wgs_covariates.txt
junctionFileList: input_files/Cerebellum_junction_paths.txt
PEER_values: '30'
VCF: input_files/chrAll_QCFinished_MAF0.01.vcf.gz
countMatrixRData: input_files/gene_matrix.RData
